module.exports = Object.freeze({
  EVENT_OAUTH_TOKEN: "EVENT_OAUTH_TOKEN",
  EVENT_OAUTH_TOKEN_DELETE: "EVENT_OAUTH_TOKEN_DELETE",
  EVENT_OAUTH_TOKEN_UPDATE: "EVENT_OAUTH_TOKEN_UPDATE",
  EVENT_OAUTH_TOKEN_INSERT: "EVENT_OAUTH_TOKEN_INSERT",
});