module.exports = {
  OAUTH_TOKEN: "OAUTH_TOKEN:",
  IP_ADDRESS_KEY: "IP_ADDRESS:",
  FM_IP_ADDRESS: "IP-ADDRESS-",

  // Concurrency Control
  // Odds
  ODDS_RESULT: "ODDS_RESULT:",
  ODDS_ABANDONED: "ODDS_ABANDONED:",
  ODDS_ROLLBACK: "ODDS_ROLLBACK:",
  // Session
  SESSION_RESULT: "SESSION_RESULT:",
  SESSION_ABANDONED: "SESSION_ABANDONED:",
  SESSION_ROLLBACK: "SESSION_ROLLBACK:",
  BET_PLACE: "BET_PLACE:",
}