const AUTHENTICATE_URL = "/v2/client/systemAuthenticate";
const LAUNCH_URL = "/launch?userToken=USER_TOKEN&systemAuthToken=PROVIDER_AUTH_TOKEN";
const RESULT_API_URL = "/v2/operator/settlement/settlementCallback/";

const UNIVERSAL_CASINO_BASE_URL = process.env.UNIVERSAL_CASINO_ENV == "development"
  ? "https://universestudio.online" : "https://universestudio.online"
  , UNIVERSAL_CASINO_USERNAME = process.env.UNIVERSAL_CASINO_ENV == "development"
    ? "avatar" : process.env.UNIVERSAL_CASINO_USERNAME
  , UNIVERSAL_CASINO_PASSWORD = process.env.UNIVERSAL_CASINO_ENV == "development"
    ? "hinxod7qihmeZapnut" : process.env.UNIVERSAL_CASINO_PASSWORD
  , UNIVERSAL_CASINO_APPKEY = process.env.UNIVERSAL_CASINO_ENV == "development"
    ? "594071aba61d374e9cd0575bfcb99d0c9bd584e63b7417fd5ee7a978ac07efb9e97498b1ee68851ebcc84761d5ee0499"
    : process.env.UNIVERSAL_CASINO_APPKEY
  , UNIVERSAL_CASINO_OPERATORID = process.env.UNIVERSAL_CASINO_ENV == "development"
    ? "65eec4883500bf6c8a169f03" : process.env.UNIVERSAL_CASINO_OPERATORID
  , UNIVERSAL_CASINO_WHITELISTING_IP = process.env.UNIVERSAL_CASINO_ENV == "development"
    ? "127.0.0.1,13.200.27.53" : process.env.UNIVERSAL_CASINO_WHITELISTING_IP
  , UNIVERSAL_CASINO_ROUTE_PATH = process.env.UNIVERSAL_CASINO_ENV == "development"
    ? "/api" : process.env.UNIVERSAL_CASINO_ROUTE_PATH;

module.exports = {
  UNIVERSAL_CASINO_USERNAME, UNIVERSAL_CASINO_PASSWORD, UNIVERSAL_CASINO_APPKEY, UNIVERSAL_CASINO_OPERATORID,
  UNIVERSAL_CASINO_WHITELISTING_IP,
  UNIVERSAL_CASINO_ROUTE_PATH,
  UNIVERSAL_CASINO_AUTHENTICATE_URL: UNIVERSAL_CASINO_BASE_URL + AUTHENTICATE_URL,
  UNIVERSAL_CASINO_LAUNCH_URL: UNIVERSAL_CASINO_BASE_URL + LAUNCH_URL,
  UNIVERSAL_CASINO_RESULT_API_URL: UNIVERSAL_CASINO_BASE_URL + RESULT_API_URL + UNIVERSAL_CASINO_APPKEY,
}