apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject-beatific-cron-backend
  namespace: default
spec:
  scaleTargetRef:
    name: {{ include "beatific-cron-backend.fullname" . }}
  minReplicaCount: 1
  triggers:
  - type: cpu
    metadata:
      type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      value: "50"