require("custom-env").env("user", require("./path").path);

module.exports = Object.freeze({
  DEFAULT_PASSWORD: process.env.DEFAULT_PASSWORD,
  DEMO_USER_ALLOWED_BET_PLACE_ON_CASINOS: process.env.DEMO_USER_ALLOWED_BET_PLACE_ON_CASINOS == "true",
  MOBILE_NO_REQUIRED: process.env.MOBILE_NO_REQUIRED == "true",
  CREF_USERS_LIST_EXPOSURE_SHOW: process.env.CREF_USERS_LIST_EXPOSURE_SHOW == "true",
  NEW_BALANCE_API: process.env.NEW_BALANCE_API == "true",
  NEW_AGENT_BALANCE_API: process.env.NEW_AGENT_BALANCE_API == "true",
  DIAMOND_USERS_LIST_EXPOSURE_SHOW: process.env.DIAMOND_USERS_LIST_EXPOSURE_SHOW == "true",
  // IS_DEFAULT_AUTH_TELEGRAM_ENABLE: process.env.IS_DEFAULT_AUTH_TELEGRAM_ENABLE == "true",
  SUPER_ADMIN_CAN_CREATE_DIRECT_AND_DOWNLINE_USER: process.env.SUPER_ADMIN_CAN_CREATE_DIRECT_AND_DOWNLINE_USER == "true",
  AGENT_CAN_CREATE_DIRECT_AND_DOWNLINE_USER: process.env.AGENT_CAN_CREATE_DIRECT_AND_DOWNLINE_USER == "true",
  TRANSACTION_PASSWORD_MAX_ATTEMPTS: parseInt(process.env.TRANSACTION_PASSWORD_MAX_ATTEMPTS),
  IS_STATEMENT_GENRATE_FOR_ZERO_SHARE: process.env.IS_STATEMENT_GENRATE_FOR_ZERO_SHARE == "true",
  AUTH_APP_JWT_SECRET: process.env.AUTH_APP_JWT_SECRET,
  DEMO_DEFAULT_AGENT_USER_NAME: process.env.DEMO_DEFAULT_AGENT_USER_NAME,
  DEMO_DEFAULT_BALANCE_CREDIT: process.env.DEMO_DEFAULT_BALANCE_CREDIT,
  USER_BLOCK_TYPE: process.env.USER_BLOCK_TYPE || 'DEFAULT',
  USER_CREATE_SPORTS_SHARE_VALIDATION: process.env.USER_CREATE_SPORTS_SHARE_VALIDATION || 'false',
  MINIMUM_WITHDRAWAL_AMOUNT: process.env.MINIMUM_WITHDRAWAL_AMOUNT * 1
});